In [1]:
### GENERATE
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TSKS33 Load data for hands-on session 5

"""

import sys
import snap
import numpy
sys.path.append("/courses/TSKS33/ht2024/common-functions")
from save_Gephi_gexf import saveGephi_gexf
from save_Gephi_gexf import saveGephi_gexf_twocolors
from gen_stochblock import gen_stoch_block_2comm



### GENERATE

#G1=gen_stoch_block_2comm(700,300,3.0/700,3.0/300,0.1/(700+300))
G1=gen_stoch_block_2comm(700,300,10.0/700,10.0/300,0.3/(700+300))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-small-network.txt")

G1=gen_stoch_block_2comm(10000,5000,3.0/10000,3.0/5000,0.1/(10000+5000))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-large-network.txt")


### LOAD FROM FILES

G = snap.LoadEdgeList(snap.PUNGraph, "test-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "test-network.mat")

G = snap.LoadEdgeList(snap.PUNGraph, "karate-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "karate-network.mat")

G = snap.LoadEdgeList(snap.PUNGraph, "SB-small-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-small-network.mat")

G = snap.LoadEdgeList(snap.PUNGraph, "SB-large-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-large-network.mat")

#G1=gen_stoch_block_2comm(700,300,3.0/700,3.0/300,0.1/(700+300))
G1=gen_stoch_block_2comm(700,300,10.0/700,10.0/300,0.3/(700+300))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-small-network.txt")

G1=gen_stoch_block_2comm(10000,5000,3.0/10000,3.0/5000,0.1/(10000+5000))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-large-network.txt")


### LOAD FROM FILES

#G = snap.LoadEdgeList(snap.PUNGraph, "test-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "test-network.mat")

#G = snap.LoadEdgeList(snap.PUNGraph, "karate-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "karate-network.mat")

#G = snap.LoadEdgeList(snap.PUNGraph, "SB-small-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-small-network.mat")

#G = snap.LoadEdgeList(snap.PUNGraph, "SB-large-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-large-network.mat")

In [2]:
#1.Karate-network.txt worked
#2.text-network.txt worked
#3.SB-small-network.txt worked
#4.SB-large-network.txt worked

In [3]:
import snap_scipy
import scipy.sparse as sp
import numpy as np
G = snap.LoadEdgeList(snap.PUNGraph, "karate-network.txt", 0, 1)
A = snap_scipy.to_sparse_mat(G)
k = np.sum(A, axis=1)

num_nodes = G.GetNodes()
num_edges = G.GetEdges()

def power_method(A):
    x = np.random.randn(num_nodes, 1)
    for _ in range(300):
        x = (A@x) - ((k@(k.T@x))/(2*num_edges))
        x /= np.linalg.norm(x)
        eig = x.T@((A@x) - ((k@(k.T@x))/(2*num_edges)))
        #eig = x.T@(v)
                
    return x, eig.item()

def find_eigenvector_corresponding_to_largest_eigen_value(A):
    x, lambda_hat = power_method(A)
    print("largest-magnitude eigenvalue: ", lambda_hat)
    if(lambda_hat>0):
        print("largest-positive eigenvalue: ", lambda_hat)
        print("largest-positive eigenvector: \n", x)
        return x, lambda_hat
    else:
        lambda_old = lambda_hat
        new_A = A-np.eye(num_nodes)*lambda_hat
        x, lambda_hat = power_method(new_A)
        print("largest-positive eigenvalue: ", lambda_hat+lambda_old)
        print("largest-positive eigenvector: \n", x)
        return x, lambda_hat



x, lambda_hat = find_eigenvector_corresponding_to_largest_eigen_value(A)

from save_Gephi_gexf import save_csrmatrix_Gephi_gexf_twocolors
save_csrmatrix_Gephi_gexf_twocolors(A, "Karate-network.gexf", x)

largest-magnitude eigenvalue:  -5.5924963427980625
largest-positive eigenvalue:  4.977080225729887
largest-positive eigenvector: 
 [[-0.38754293]
 [-0.26955742]
 [-0.13189899]
 [-0.25345236]
 [-0.13400323]
 [-0.14573804]
 [-0.14573804]
 [-0.20935954]
 [ 0.05447571]
 [-0.13400323]
 [-0.07784279]
 [-0.12874396]
 [-0.13502861]
 [-0.13197981]
 [-0.05764888]
 [-0.13197981]
 [ 0.10185678]
 [ 0.09626391]
 [ 0.04785238]
 [ 0.10276487]
 [ 0.06834027]
 [ 0.32390453]
 [-0.05851821]
 [ 0.36983786]
 [ 0.13943288]
 [ 0.13943288]
 [ 0.13943288]
 [ 0.13943288]
 [ 0.13943288]
 [ 0.21674712]
 [ 0.07540039]
 [ 0.20629456]
 [ 0.0563305 ]
 [ 0.11580257]]


In [4]:
import snap_scipy
import scipy.sparse as sp
import numpy as np
G = snap.LoadEdgeList(snap.PUNGraph, "test-network.txt", 0, 1)
A = snap_scipy.to_sparse_mat(G)
k = np.sum(A, axis=1)

num_nodes = G.GetNodes()
num_edges = G.GetEdges()

print("test")

x, lambda_hat = find_eigenvector_corresponding_to_largest_eigen_value(A)

from save_Gephi_gexf import save_csrmatrix_Gephi_gexf_twocolors
save_csrmatrix_Gephi_gexf_twocolors(A, "test.gexf", x)

A = snap_scipy.to_sparse_mat(G)
k = np.sum(A, axis=1)
num_edges = G.GetEdges()
kkt = np.outer(k, k)/(2*num_edges)
kkt_sparse = sp.csr_matrix(kkt)
Z = A - kkt_sparse

s = np.where(x > 0, 1, -1)

Q = (s.T@Z.toarray()@s)/(4*num_edges)


print("modularity: ", Q)

test
largest-magnitude eigenvalue:  -1.9192868848312756
largest-positive eigenvalue:  1.3549980049551589
largest-positive eigenvector: 
 [[-0.37200009]
 [-0.45877098]
 [-0.37200009]
 [ 0.25823163]
 [ 0.47226977]
 [ 0.47226977]]
modularity:  [[0.31944444]]


In [5]:
import snap_scipy
import scipy.sparse as sp
import numpy as np
G = snap.LoadEdgeList(snap.PUNGraph, "SB-small-network.txt", 0, 1)
A = snap_scipy.to_sparse_mat(G)
k = np.sum(A, axis=1)

num_nodes = G.GetNodes()
num_edges = G.GetEdges()

print("sb-small")

x, lambda_hat = find_eigenvector_corresponding_to_largest_eigen_value(A)

from save_Gephi_gexf import save_csrmatrix_Gephi_gexf_twocolors
save_csrmatrix_Gephi_gexf_twocolors(A, "sb-small.gexf", x)

A = snap_scipy.to_sparse_mat(G)
k = np.sum(A, axis=1)
num_edges = G.GetEdges()
kkt = np.outer(k, k)/(2*num_edges)
kkt_sparse = sp.csr_matrix(kkt)
Z = A - kkt_sparse

s = np.where(x > 0, 1, -1)

Q = (s.T@Z.toarray()@s)/(4*num_edges)


print("modularity: ", Q)

sb-small
largest-magnitude eigenvalue:  11.328276370149464
largest-positive eigenvalue:  11.328276370149464
largest-positive eigenvector: 
 [[-0.00524619]
 [-0.01549022]
 [-0.02208428]
 [-0.01921249]
 [-0.02427248]
 [-0.02359423]
 [-0.01307496]
 [-0.02317992]
 [-0.01931094]
 [-0.02660693]
 [-0.0145375 ]
 [-0.02679451]
 [-0.01211677]
 [-0.02523505]
 [-0.01890255]
 [-0.02000609]
 [-0.02617819]
 [-0.01397334]
 [-0.02729261]
 [-0.0240361 ]
 [-0.02274185]
 [-0.00955303]
 [-0.02443834]
 [-0.02027721]
 [-0.01502006]
 [-0.01175025]
 [-0.01684902]
 [-0.01329512]
 [-0.02602242]
 [-0.02604914]
 [-0.02758945]
 [-0.04031816]
 [-0.018368  ]
 [-0.0400752 ]
 [-0.02855058]
 [-0.02398666]
 [-0.02181021]
 [-0.03282082]
 [-0.03249244]
 [-0.0361575 ]
 [-0.02199639]
 [ 0.03774197]
 [-0.03581211]
 [-0.01048632]
 [-0.01434294]
 [-0.01551531]
 [-0.03959571]
 [-0.03592844]
 [-0.03273001]
 [-0.03363327]
 [-0.02045394]
 [-0.01835059]
 [-0.03477149]
 [-0.02771127]
 [-0.02518957]
 [-0.02706895]
 [-0.03503988]
 [-0.

In [6]:
G = snap.LoadEdgeList(snap.PUNGraph, "SB-large-network.txt", 0, 1)

num_nodes = G.GetNodes()
num_edges = G.GetEdges()
import scipy.sparse as sp
import numpy as np

def create_sparse_matrix(snapGraph: snap.PUNGraph):
    rows = []
    cols = []
    data = []
    
    for edge in G.Edges():
        rows.append(edge.GetSrcNId()-1)
        cols.append(edge.GetDstNId()-1)
        data.append(1) 
    coo_matrix = sp.coo_matrix((data, (rows, cols)), shape=(num_nodes, num_nodes))
    return coo_matrix



def getA(snapGraph: snap.PUNGraph):
    A = np.zeros((num_nodes, num_nodes))
    for edge in snapGraph.Edges():
        A[edge.GetSrcNId()-1][edge.GetDstNId()-1] = 1
    return A
    
def getZ(sparse_matrix: sp.coo_matrix):
    sub_matrix = np.ones((num_nodes, num_nodes))/(2*num_edges)
    result_matrix = sp.coo_matrix(sparse_matrix.toarray()-sub_matrix)
    return result_matrix

def getK(snapGraph: snap.PUNGraph):
    i = 0
    k = np.zeros(num_nodes)
    for node in snapGraph.Nodes():
        k[i] = node.GetDeg()
        i+=1
    return k
    

In [7]:
import snap_scipy
import scipy.sparse as sp
import numpy as np
G = snap.LoadEdgeList(snap.PUNGraph, "SB-large-network.txt", 0, 1)
A = snap_scipy.to_sparse_mat(G)
k = np.sum(A, axis=1)

num_nodes = G.GetNodes()
num_edges = G.GetEdges()

print("sb-large")

x, lambda_hat = find_eigenvector_corresponding_to_largest_eigen_value(A)

from save_Gephi_gexf import save_csrmatrix_Gephi_gexf_twocolors
save_csrmatrix_Gephi_gexf_twocolors(A, "sb-large.gexf", x)

A = snap_scipy.to_sparse_mat(G)
k = np.sum(A, axis=1)
num_edges = G.GetEdges()
kkt = np.outer(k, k)/(2*num_edges)
kkt_sparse = sp.csr_matrix(kkt)
Z = A - kkt_sparse

s = np.where(x > 0, 1, -1)

Q = (s.T@Z.toarray()@s)/(4*num_edges)

print("modularity: ", Q)

sb-large
largest-magnitude eigenvalue:  1.5158498681803287
largest-positive eigenvalue:  1.5158498681803287
largest-positive eigenvector: 
 [[ 0.00231529]
 [ 0.00056385]
 [ 0.00014351]
 ...
 [-0.00120261]
 [-0.00522191]
 [-0.01945642]]
modularity:  [[0.25092794]]
